# Generated by Django 4.2.1 on 2023-05-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodOrder',
            new_name='CommandeSang',
        ),
        migrations.RenameModel(
            old_name='Donor',
            new_name='Donneur',
        ),
        migrations.RenameModel(
            old_name='BloodBag',
            new_name='PocheDeSang',
        ),
        migrations.RenameModel(
            old_name='BloodStock',
            new_name='StockDeSang',
        ),
    ]
