# Generated by Django 4.2.1 on 2023-05-26 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DonorApp', '0002_rename_bloodorder_commandesang_rename_donor_donneur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='Type de sang'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date naissance'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier date de don'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='donneur',
            name='rh_factor',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1, verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='stockdesang',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='Type Sang'),
        ),
        migrations.AlterField(
            model_name='stockdesang',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stockdesang',
            name='rh_factor',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1, verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='Type Sang'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='recipient',
            field=models.CharField(max_length=100, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='transfusion',
            name='rh_factor',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1, verbose_name='RH'),
        ),
    ]
