# Generated by Django 4.2.1 on 2023-05-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonorApp', '0003_alter_donneur_additional_notes_alter_donneur_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='Type Sang'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date naissance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='required_date',
            field=models.DateField(verbose_name='Date requise'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rh_factor',
            field=models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1, verbose_name='RH'),
        ),
    ]
